  spring :
    profiles:
      active: dev
    application:
      name: doors-api-gateway1

    redis:
      port: 6379
      password: password
      host: localhost
      maxclients: 800

  server:
    port: 5003
    servlet:
      context-path  : /doors-api

  eureka:
      client:
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

  zuul:
    routes:
        prefix: doors-api
        usermanagement:
           path: /users/**
           serviceId: doors-usermanagement
           stripPrefix: false
  ribbon:
    eureka:
      enabled: true
