spring :
  profiles:
    active: dev
  application:
    name: doors-api-gateway
  #datasource:
   # url: jdbc:mariadb://localhost:3306/doors
   # username: root
    #password: root
    #driver-class-name: org.mariadb.jdbc.Driver
  datasource:
    url: jdbc:h2:mem:testdb
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
   # database-platform: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  redis:
      port: 6379
      password: password
      host: localhost
      maxclients: 800

server:
  port: 8081
  servlet:
    context-path  : /doors-api

eureka:
    client:
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/