spring :
  profiles:
    active: dev
  application:
    name: doors-api-gateway
  datasource:
    url: jdbc:mariadb://localhost:3306/doors
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8081


eureka:
    client:
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/